# Form implementation generated from reading ui file 'main_window_d.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet(
            "background-color:qlineargradient(spread:pad, x1:0.134, y1:0.187, x2:1, y2:0.954, stop:0.0458404 rgba(1, 180, 148, 255), stop:1 rgba(65, 215, 154, 255));")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_select_a_file = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_select_a_file.setGeometry(QtCore.QRect(60, 40, 700, 50))
        self.btn_select_a_file.setMinimumSize(QtCore.QSize(700, 50))
        self.btn_select_a_file.setMaximumSize(QtCore.QSize(700, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_select_a_file.setFont(font)
        self.btn_select_a_file.setStyleSheet("QPushButton{\n"
                                             "background-color:rgba(255,255,255,30);\n"
                                             "border:1px solid rgba(255,255,255,40);\n"
                                             "border-radius:7px;\n"
                                             "width: 400px;\n"
                                             "height: 100px;\n"
                                             "}\n"
                                             "QPushButton:hover{\n"
                                             "background-color:rgba(255,255,255,40);\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:pressed{\n"
                                             "background-color:rgba(255,255,255,90);\n"
                                             "}")
        self.btn_select_a_file.setObjectName("btn_select_a_file")
        self.btn_confirm_choice = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_confirm_choice.setGeometry(QtCore.QRect(60, 410, 340, 51))
        self.btn_confirm_choice.setMinimumSize(QtCore.QSize(340, 50))
        self.btn_confirm_choice.setBaseSize(QtCore.QSize(340, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_confirm_choice.setFont(font)
        self.btn_confirm_choice.setStyleSheet("QPushButton{\n"
                                              "background-color:rgba(255,255,255,30);\n"
                                              "border:1px solid rgba(255,255,255,40);\n"
                                              "border-radius:7px;\n"
                                              "width: 340px;\n"
                                              "height: 50px;\n"
                                              "}\n"
                                              "QPushButton:hover{\n"
                                              "background-color:rgba(255,255,255,40);\n"
                                              "}\n"
                                              "\n"
                                              "QPushButton:pressed{\n"
                                              "background-color:rgba(255,255,255,90);\n"
                                              "}")
        self.btn_confirm_choice.setObjectName("btn_confirm_choice")
        self.btn_save = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(420, 410, 340, 50))
        self.btn_save.setMinimumSize(QtCore.QSize(340, 50))
        self.btn_save.setMaximumSize(QtCore.QSize(340, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_save.setFont(font)
        self.btn_save.setStyleSheet("QPushButton{\n"
                                    "background-color:rgba(255,255,255,30);\n"
                                    "border:1px solid rgba(255,255,255,40);\n"
                                    "border-radius:7px;\n"
                                    "width: 340px;\n"
                                    "height: 50px;\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "background-color:rgba(255,255,255,40);\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:pressed{\n"
                                    "background-color:rgba(255,255,255,90);\n"
                                    "}")
        self.btn_save.setObjectName("btn_save")
        self.selected_files = QtWidgets.QLabel(parent=self.centralwidget)
        self.selected_files.setGeometry(QtCore.QRect(60, 110, 700, 20))
        self.selected_files.setMinimumSize(QtCore.QSize(700, 20))
        self.selected_files.setMaximumSize(QtCore.QSize(700, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selected_files.setFont(font)
        self.selected_files.setStyleSheet("background-color:none;")
        self.selected_files.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignBottom | QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft)
        self.selected_files.setObjectName("selected_files")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(60, 140, 701, 231))
        self.tableWidget.setStyleSheet("background-color: rgb(63, 63, 63);\n"
                                       "border: 1px solid rgba(255,255,255, 100);\n"
                                       "border-radius: 7px;\n"
                                       "color:white;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.btn_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(60, 510, 700, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("QPushButton{\n"
                                    "background-color:rgba(255,255,255,30);\n"
                                    "border:1px solid rgba(255,255,255,40);\n"
                                    "border-radius:7px;\n"
                                    "width: 400px;\n"
                                    "height: 100px;\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "background-color:rgba(255,255,255,40);\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:pressed{\n"
                                    "background-color:rgba(255,255,255,90);\n"
                                    "}")
        self.btn_exit.setObjectName("btn_exit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Success Employee"))
        self.btn_select_a_file.setText(_translate("MainWindow", "Выбрать один или несколько файлов"))
        self.btn_confirm_choice.setText(_translate("MainWindow", "Подтвердить выбор"))
        self.btn_save.setText(_translate("MainWindow", "Сохранить результат в txt файл"))
        self.selected_files.setText(_translate("MainWindow", "Выбранный файл:"))
        self.btn_exit.setText(_translate("MainWindow", "Выход"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
